import { writeFile, mkdir } from "fs/promises";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { routes } from "../api/routes";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outputPath = resolve(__dirname, "../../../cli/src/generated/api-client.ts");

const apiPrefix = "/api/v1";
const { listDocs, getDocById, getDocBySlug, createDoc, updateDoc } = routes;
const listPath = `${apiPrefix}${listDocs.path}`;
const getDocByIdPath = `${apiPrefix}${getDocById.path}`;
const getDocBySlugPath = `${apiPrefix}${getDocBySlug.path}`;
const createDocPath = `${apiPrefix}${createDoc.path}`;
const updateDocPath = `${apiPrefix}${updateDoc.path}`;

const lines = [
  "// AUTO-GENERATED BY backend/src/codegen/generate-client.ts",
  "/* eslint-disable */",
  "export type DocFrontmatter = {",
  "  id: string;",
  "  slug: string;",
  "  title: string;",
  "  summary: string;",
  "  version: number;",
  "  updatedAt: string;",
  "};",
  "",
  "export type DocWithContent = {",
  "  id: string;",
  "  slug: string;",
  "  version: number;",
  "  updatedAt: string;",
  "  frontmatter: { title: string; summary: string };",
  "  content: string;",
  "};",
  "",
  "export type CreateDocRequest = {",
  "  slug?: string;",
  "  title: string;",
  "  summary: string;",
  "  content: string;",
  "};",
  "",
  "export type UpdateDocRequest = {",
  "  title?: string;",
  "  summary?: string;",
  "  content?: string;",
  "};",
  "",
  "export type ApiError = {",
  "  error: string;",
  "  message: string;",
  "};",
  "",
  "export class ApiClient {",
  "  constructor(private config: { baseUrl: string }) {}",
  "",
  "  private async request<T>(path: string, init?: RequestInit): Promise<T> {",
  "    const res = await fetch(this.config.baseUrl + path, {",
  "      ...init,",
  "      headers: { \"content-type\": \"application/json\", ...(init?.headers || {}) },",
  "    });",
  "    if (!res.ok) {",
  "      const body = await res.text();",
  "      throw new Error(\"HTTP \" + res.status + \": \" + body);",
  "    }",
  "    return (await res.json()) as T;",
  "  }",
  "",
  "  async listDocs(): Promise<{ docs: DocFrontmatter[] }> {",
  `    return this.request("${listPath}");`,
  "  }",
  "",
  "  async getDocById(id: string): Promise<DocWithContent> {",
  `    return this.request("${getDocByIdPath}".replace(":id", id));`,
  "  }",
  "",
  "  async getDocBySlug(slug: string): Promise<DocWithContent> {",
  `    return this.request("${getDocBySlugPath}".replace(":slug", slug));`,
  "  }",
  "",
  "  async createDoc(body: CreateDocRequest): Promise<DocWithContent> {",
  `    return this.request("${createDocPath}", {`,
  "      method: \"POST\",",
  "      body: JSON.stringify(body),",
  "    });",
  "  }",
  "",
  "  async updateDoc(id: string, body: UpdateDocRequest): Promise<DocWithContent> {",
  `    return this.request("${updateDocPath}".replace(":id", id), {`,
  "      method: \"PUT\",",
  "      body: JSON.stringify(body),",
  "    });",
  "  }",
  "}",
  "",
];

const fileContent = lines.join("\n");

async function main() {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, fileContent, "utf8");
  console.log(`Wrote client to ${outputPath}`);
}

if (import.meta.main) {
  void main();
}
